name: Karabiner-Elements CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: recursive
      - name: xcode-select
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: package
        run: make package
      - name: upload
        uses: actions/upload-artifact@v2.1.4
        with:
          name: Karabiner-Elements-12.90.12.dmg
          path: Karabiner-Elements-12.90.12.dmg
